import {
  Patient,
  Memory,
  Reminder,
  Activity,
  Caregiver,
  Practitioner,
  Observation,
  LoveNote,
  Narration,
  Alert,
} from '@/types/models';

// ==========================================
// 1. PATIENTS (Minimum 3: Kamal, Meera, Balram, Sarojini)
// ==========================================
export const SEED_PATIENTS: Patient[] = [
  {
    id: 'p-101',
    name: 'Kamal Sharma',
    preferredName: 'Papa',
    relationToCaregiver: 'Father',
    age: 74,
    gender: 'Male',
    condition: 'Mild Cognitive Impairment (Amnestic)',
    stage: 'early',
    location: 'Greater Kailash II, New Delhi',
    currentStatus: 'Relaxing in Living Room • Calm & Oriented',
    mood: 'calm',
    todayEngagement: 84,
    primaryCaregiverId: 'cg-01',
    primaryCaregiverName: 'Heena Sharma',
    primaryCaregiverPhone: '+91 98922 56502',
    attendingPhysician: 'Dr. Arvind Sen, MD',
    onboardingDate: '2026-01-12',
    daysActive: 54,
    engagementScore: 84,
    engagementTrend: 'improving',
    memoryActivityScore: 88,
    routineAdherenceScore: 91,
    lastInteraction: '28 mins ago (Afternoon Chai Routine)',
    riskIndicator: 'optimal',
    riskLabel: 'Optimal Stability',
    riskContextNote: 'High consistency with morning sitar reminiscing and prompt Donepezil intake.',
    primaryNostalgicTriggers: [
      'Jaipur 1960s civil engineering projects',
      'Delhi University convocation (1972)',
      'Classical Sitar (Raga Yaman)',
      'Terrace monsoon tea',
    ],
    activeMedications: [
      { name: 'Donepezil Hydrochloride', dosage: '5mg', timing: 'Morning (08:00 AM)', adherenceRate: 96 },
      { name: 'Amlodipine (Blood Pressure)', dosage: '5mg', timing: 'Morning (09:00 AM)', adherenceRate: 92 },
      { name: 'Melatonin & Calcium Citrate', dosage: '3mg/500mg', timing: 'Bedtime (09:30 PM)', adherenceRate: 88 },
    ],
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    weeklyHistory: [
      { day: 'Mon', engagement: 82, memory: 85, adherence: 90 },
      { day: 'Tue', engagement: 86, memory: 90, adherence: 95 },
      { day: 'Wed', engagement: 80, memory: 82, adherence: 88 },
      { day: 'Thu', engagement: 88, memory: 92, adherence: 92 },
      { day: 'Fri', engagement: 85, memory: 88, adherence: 90 },
      { day: 'Sat', engagement: 90, memory: 94, adherence: 95 },
      { day: 'Sun', engagement: 84, memory: 88, adherence: 91 },
    ],
    createdAt: '2026-01-12T08:00:00Z',
    updatedAt: '2026-09-09T08:00:00Z',
  },
  {
    id: 'p-102',
    name: 'Meera Iyer',
    preferredName: 'Meera-ji',
    relationToCaregiver: 'Mother',
    age: 71,
    gender: 'Female',
    condition: 'Early-stage Alzheimer’s Disease',
    stage: 'early',
    location: 'Bapu Nagar, Jaipur',
    currentStatus: 'Listening to Sitar • Radiant & Nostalgic',
    mood: 'cheerful',
    todayEngagement: 78,
    primaryCaregiverId: 'cg-02',
    primaryCaregiverName: 'Rohan Iyer',
    primaryCaregiverPhone: '+91 97234 11200',
    attendingPhysician: 'Dr. Arvind Sen, MD',
    onboardingDate: '2026-02-04',
    daysActive: 31,
    engagementScore: 78,
    engagementTrend: 'stable',
    memoryActivityScore: 74,
    routineAdherenceScore: 86,
    lastInteraction: '1 hr ago (Carnatic Voice Prompt)',
    riskIndicator: 'optimal',
    riskLabel: 'Steady Rhythm',
    riskContextNote: 'Responsive to family photos from Mysore; occasional hesitation during dusk hours.',
    primaryNostalgicTriggers: [
      'Carnatic vocal music (M.S. Subbulakshmi)',
      'Mysore silk saree weaving tradition',
      'Grandchildren school recitals',
    ],
    activeMedications: [
      { name: 'Rivastigmine Patch', dosage: '4.6mg/24h', timing: 'Morning (09:00 AM)', adherenceRate: 94 },
      { name: 'CoQ10 Supplement', dosage: '100mg', timing: 'Lunch (01:00 PM)', adherenceRate: 85 },
    ],
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    weeklyHistory: [
      { day: 'Mon', engagement: 74, memory: 70, adherence: 84 },
      { day: 'Tue', engagement: 78, memory: 75, adherence: 88 },
      { day: 'Wed', engagement: 72, memory: 68, adherence: 82 },
      { day: 'Thu', engagement: 80, memory: 76, adherence: 90 },
      { day: 'Fri', engagement: 76, memory: 72, adherence: 85 },
      { day: 'Sat', engagement: 82, memory: 80, adherence: 88 },
      { day: 'Sun', engagement: 78, memory: 74, adherence: 86 },
    ],
    createdAt: '2026-02-04T09:30:00Z',
    updatedAt: '2026-09-09T08:30:00Z',
  },
  {
    id: 'p-103',
    name: 'Balram Verma',
    preferredName: 'Balram-ji',
    relationToCaregiver: 'Father',
    age: 79,
    gender: 'Male',
    condition: 'Vascular Cognitive Impairment',
    stage: 'moderate',
    location: 'Hazratganj, Lucknow',
    currentStatus: 'Resting after garden walk',
    mood: 'pensive',
    todayEngagement: 62,
    primaryCaregiverId: 'cg-03',
    primaryCaregiverName: 'Sunita Verma',
    primaryCaregiverPhone: '+91 94500 89211',
    attendingPhysician: 'Dr. Sunita Kulkarni, MD',
    onboardingDate: '2025-11-20',
    daysActive: 108,
    engagementScore: 65,
    engagementTrend: 'declining',
    memoryActivityScore: 58,
    routineAdherenceScore: 72,
    lastInteraction: '2 hrs ago (Hydration Reminder)',
    riskIndicator: 'attention',
    riskLabel: 'Moderate Fluctuation',
    riskContextNote: 'Evening sundowning symptoms reported twice this week; hydration adherence dropped slightly.',
    primaryNostalgicTriggers: [
      'Lucknow railway station architecture',
      'Awadhi culinary memories and kebabs',
      'Urdu poetry recitals at Baradari',
    ],
    activeMedications: [
      { name: 'Memantine HCl', dosage: '10mg', timing: 'Morning (08:30 AM)', adherenceRate: 78 },
      { name: 'Clopidogrel', dosage: '75mg', timing: 'Breakfast (09:00 AM)', adherenceRate: 85 },
    ],
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    weeklyHistory: [
      { day: 'Mon', engagement: 68, memory: 60, adherence: 75 },
      { day: 'Tue', engagement: 64, memory: 58, adherence: 70 },
      { day: 'Wed', engagement: 60, memory: 55, adherence: 68 },
      { day: 'Thu', engagement: 66, memory: 62, adherence: 74 },
      { day: 'Fri', engagement: 58, memory: 52, adherence: 65 },
      { day: 'Sat', engagement: 65, memory: 60, adherence: 72 },
      { day: 'Sun', engagement: 62, memory: 58, adherence: 70 },
    ],
    createdAt: '2025-11-20T10:00:00Z',
    updatedAt: '2026-09-09T07:15:00Z',
  },
  {
    id: 'p-104',
    name: 'Sarojini Devi',
    preferredName: 'Mata-ji',
    relationToCaregiver: 'Mother',
    age: 82,
    gender: 'Female',
    condition: 'Mild Cognitive Impairment with Lewy Body Tendency',
    stage: 'moderate',
    location: 'Sector 17, Chandigarh',
    currentStatus: 'Gentle puzzle activity with companion',
    mood: 'calm',
    todayEngagement: 72,
    primaryCaregiverId: 'cg-04',
    primaryCaregiverName: 'Vikram Patel',
    primaryCaregiverPhone: '+91 98881 23450',
    attendingPhysician: 'Dr. Arvind Sen, MD',
    onboardingDate: '2026-01-28',
    daysActive: 38,
    engagementScore: 71,
    engagementTrend: 'stable',
    memoryActivityScore: 68,
    routineAdherenceScore: 80,
    lastInteraction: '45 mins ago (Find the Object Game)',
    riskIndicator: 'optimal',
    riskLabel: 'Calm Baseline',
    riskContextNote: 'High benefit from auditory cues and soothing bhajan chants before noon.',
    primaryNostalgicTriggers: [
      'Punjab agricultural golden wheat harvest',
      'Folk wedding songs with dholak',
      'Clay tandoor baking stories',
    ],
    activeMedications: [
      { name: 'Rivastigmine', dosage: '3mg', timing: 'Twice daily', adherenceRate: 88 },
    ],
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-28T11:00:00Z',
    updatedAt: '2026-09-09T08:10:00Z',
  },
];

// ==========================================
// 2. CAREGIVERS (Multiple)
// ==========================================
export const SEED_CAREGIVERS: Caregiver[] = [
  {
    id: 'cg-01',
    name: 'Heena Sharma',
    preferredName: 'Heena',
    relation: 'Daughter',
    phone: '+91 98922 56502',
    email: 'heena.sharma@example.com',
    associatedPatientIds: ['p-101'],
    validationFrequency: 'Twice daily',
    receiveInstantAlerts: true,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-12T08:00:00Z',
  },
  {
    id: 'cg-02',
    name: 'Rohan Iyer',
    preferredName: 'Rohan',
    relation: 'Son',
    phone: '+91 97234 11200',
    email: 'rohan.iyer@example.com',
    associatedPatientIds: ['p-102'],
    validationFrequency: 'Daily evening',
    receiveInstantAlerts: true,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-02-04T09:30:00Z',
  },
  {
    id: 'cg-03',
    name: 'Sunita Verma',
    preferredName: 'Sunita',
    relation: 'Daughter-in-law',
    phone: '+91 94500 89211',
    email: 'sunita.verma@example.com',
    associatedPatientIds: ['p-103'],
    validationFrequency: 'Continuous / Co-residing',
    receiveInstantAlerts: true,
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-11-20T10:00:00Z',
  },
  {
    id: 'cg-04',
    name: 'Vikram Patel',
    preferredName: 'Vikram',
    relation: 'Nephew',
    phone: '+91 98881 23450',
    email: 'vikram.patel@example.com',
    associatedPatientIds: ['p-104'],
    validationFrequency: 'Daily check-in',
    receiveInstantAlerts: false,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-28T11:00:00Z',
  },
];

// ==========================================
// 3. PRACTITIONERS (Multiple)
// ==========================================
export const SEED_PRACTITIONERS: Practitioner[] = [
  {
    id: 'dr-01',
    name: 'Dr. Arvind Sen',
    title: 'MD (Neurology), DNB',
    specialty: 'Cognitive Neurology & Geriatric Memory Care',
    hospital: 'All India Institute of Medical Sciences (AIIMS), New Delhi',
    email: 'arvind.sen@aiims.edu',
    phone: '+91 11 2658 8500',
    assignedPatientIds: ['p-101', 'p-102', 'p-104'],
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-10-01T09:00:00Z',
  },
  {
    id: 'dr-02',
    name: 'Dr. Sunita Kulkarni',
    title: 'MD, Geriatric Medicine',
    specialty: 'Geriatric Rehabilitation & Neuro-psychiatry',
    hospital: 'King George’s Medical University, Lucknow',
    email: 'dr.kulkarni@kgmu.org',
    phone: '+91 522 225 7450',
    assignedPatientIds: ['p-103'],
    avatarUrl: 'https://images.unsplash.com/photo-1594824813589-4b68e98b725c?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-10-15T10:00:00Z',
  },
  {
    id: 'dr-03',
    name: 'Nalini Raman',
    title: 'M.Sc, Occupational Therapy',
    specialty: 'Reminiscence Therapy & Sensory Stimulation',
    hospital: 'Cognitive Wellness Center, New Delhi',
    email: 'nalini.raman@wellness.in',
    phone: '+91 11 4100 2930',
    assignedPatientIds: ['p-101', 'p-102'],
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-11-01T10:00:00Z',
  },
];

// ==========================================
// 4. MEMORIES (Minimum 15 - Detailed & Rich)
// ==========================================
export const SEED_MEMORIES: Memory[] = [
  {
    id: 'childhood-home',
    patientId: 'p-101',
    title: 'My Childhood Home & Courtyard',
    shortDescription: 'The open brick courtyard in Jaipur where we played under the mango tree every afternoon.',
    dateEra: '1962 • Jaipur, Rajasthan',
    yearApproximate: '1962',
    location: 'Bapu Nagar, Jaipur',
    category: 'childhood',
    emotionalTag: 'Warm Nostalgia',
    emotionalColor: 'bg-amber-100 text-amber-900 border-amber-300',
    companionIntro: 'This is your ancestral courtyard in Jaipur, where your mother sang morning hymns.',
    coverImage: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1200&auto=format&fit=crop&q=80',
    imageAlt: 'Sunlit traditional brick courtyard with potted plants and warm light',
    imageCaption: 'The courtyard veranda where afternoon tea was poured into clay kulhads.',
    familiarPeople: ['Maa (Mother)', 'Bapuji (Father)', 'Elder Sister Shanti'],
    isMemoryOfTheDay: true,
    createdAt: '2026-08-15T09:00:00Z',
    updatedAt: '2026-09-08T10:00:00Z',
    story: [
      'Every morning began with the rhythmic sound of the courtyard hand pump and the fragrant scent of night-blooming jasmine.',
      'Under the big mango tree in the corner, grandmother spread clean white cotton sheets where we helped shell fresh green peas and listened to folklore from the desert hills.',
      'Whenever the summer breeze blew, the brass wind chimes by the main wooden doorway danced, filling the whole courtyard with a soothing ring that felt like safety itself.'
    ],
    familyNotes: [
      {
        id: 'fn-1',
        patientId: 'p-101',
        memoryId: 'childhood-home',
        authorId: 'cg-02',
        authorName: 'Rohan',
        relation: 'Son',
        text: 'Papa, whenever you speak about the big courtyard, your eyes sparkle. You taught all of us how to love open skies right there.',
        date: 'Added yesterday',
        avatarInitials: 'R',
        avatarBg: 'bg-orange-500',
        createdAt: '2026-09-08T09:00:00Z',
      },
      {
        id: 'fn-2',
        patientId: 'p-101',
        memoryId: 'childhood-home',
        authorId: 'cg-01',
        authorName: 'Priya',
        relation: 'Daughter',
        text: 'I kept the little brass diya that Grandma gave you from that house on my study desk. It reminds me of your kindness.',
        date: '3 days ago',
        avatarInitials: 'P',
        avatarBg: 'bg-emerald-600',
        createdAt: '2026-09-06T11:00:00Z',
      },
    ],
    audioNarration: {
      narrator: 'Priya (Daughter)',
      relation: 'Recorded with love',
      duration: '1:45',
      title: 'A Courtyard of Memories',
    },
  },
  {
    id: 'school-graduation',
    patientId: 'p-101',
    title: 'College Graduation at Delhi University',
    shortDescription: 'Walking across the convocation hall receiving your engineering degree with first-class honors.',
    dateEra: '1974 • Delhi College of Engineering',
    yearApproximate: '1974',
    location: 'Kashmere Gate, Delhi University',
    category: 'school',
    emotionalTag: 'Pride & Achievement',
    emotionalColor: 'bg-blue-100 text-blue-900 border-blue-300',
    companionIntro: 'Look at you on graduation day! You worked so diligently for your degree in civil engineering.',
    coverImage: 'https://images.unsplash.com/photo-1627556704290-2b1f5853ff78?w=1200&auto=format&fit=crop&q=80',
    imageAlt: 'Graduation cap and open leather-bound literature books bathed in morning sunlight',
    imageCaption: 'Class of 1974. You stood first in structural mechanics and surveying.',
    familiarPeople: ['Dean Sen', 'Best Friend Anuradha', 'Bapuji'],
    isMemoryOfTheDay: false,
    createdAt: '2026-08-16T10:00:00Z',
    updatedAt: '2026-09-07T12:00:00Z',
    story: [
      'The morning was crisp in old Delhi. You wore your handloom ivory kurta with pride, holding your certificate folder close to your heart.',
      'Bapuji travelled overnight by train just to sit in the third row. When your name was called, he stood up and clapped with tears of pure pride.',
      'After the ceremony, you and your classmates shared hot samosas and sweet tea at the university canteen, dreaming of all the bridges you would build.'
    ],
    familyNotes: [
      {
        id: 'fn-3',
        patientId: 'p-101',
        memoryId: 'school-graduation',
        authorId: 'cg-02',
        authorName: 'Rohan',
        relation: 'Son',
        text: 'You are our greatest teacher, Papa. Your dedication and integrity made our childhood rich in curiosity.',
        date: 'Last week',
        avatarInitials: 'R',
        avatarBg: 'bg-orange-500',
        createdAt: '2026-09-02T10:00:00Z',
      },
    ],
    audioNarration: {
      narrator: 'Rohan (Son)',
      relation: 'Family story',
      duration: '2:10',
      title: 'Grandpa’s Proudest Morning',
    },
  },
  {
    id: 'wedding-day',
    patientId: 'p-101',
    title: 'Our Wedding Day with Meera',
    shortDescription: 'Fresh red roses, fragrant marigold garlands, and the holy fire in Agra.',
    dateEra: 'December 1976 • Civil Lines, Agra',
    yearApproximate: '1976',
    location: 'Civil Lines, Agra',
    category: 'celebrations',
    emotionalTag: 'Lifelong Love',
    emotionalColor: 'bg-rose-100 text-rose-900 border-rose-300',
    companionIntro: 'Here is you and Meera on your wedding day. Fifty years of deep companionship.',
    coverImage: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1200&auto=format&fit=crop&q=80',
    imageAlt: 'Traditional red and golden silk wedding fabric with fragrant marigold flower garlands',
    imageCaption: 'Surrounded by close relatives singing wedding folk songs into the midnight hour.',
    familiarPeople: ['Meera (Wife)', 'Grandmother Parvati', 'Brother Ashok'],
    isMemoryOfTheDay: false,
    createdAt: '2026-08-17T11:00:00Z',
    updatedAt: '2026-09-07T14:00:00Z',
    story: [
      'The winter evening was cool, but the wedding hall was glowing with clay lamps and brass incense burners.',
      'Meera arrived looking radiant in crimson Banarasi silk. When the shehnai music played Raga Bilawal, all the cousins were laughing and throwing rose petals.',
      'You promised that every Sunday morning, you would listen to classical morning ragas together over ginger tea—a promise kept for five decades.'
    ],
    familyNotes: [
      {
        id: 'fn-4',
        patientId: 'p-101',
        memoryId: 'wedding-day',
        authorId: 'cg-01',
        authorName: 'Priya',
        relation: 'Daughter',
        text: 'The look of tenderness between you and Ma in this wedding album has always been my definition of true companionship.',
        date: '4 days ago',
        avatarInitials: 'P',
        avatarBg: 'bg-emerald-600',
        createdAt: '2026-09-05T12:00:00Z',
      },
    ],
    audioNarration: {
      narrator: 'Priya (Daughter)',
      relation: 'Family story',
      duration: '2:30',
      title: 'The Song of Two Hearts',
    },
  },
  {
    id: 'family-picnic-lodi',
    patientId: 'p-101',
    title: 'Spring Picnic at Lodi Gardens',
    shortDescription: 'Rohan running after colorful butterflies while Priya drew chalk animals on the stone bench.',
    dateEra: 'March 1986 • New Delhi',
    yearApproximate: '1986',
    location: 'Lodi Gardens, New Delhi',
    category: 'family',
    emotionalTag: 'Pure Joy',
    emotionalColor: 'bg-emerald-100 text-emerald-900 border-emerald-300',
    companionIntro: 'A beautiful sunny Sunday at Lodi Gardens with little Rohan and Priya.',
    coverImage: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=1200&auto=format&fit=crop&q=80',
    imageAlt: 'Green sunlit garden lawn with blooming flowers and picnic blanket',
    imageCaption: 'The stainless steel tiffin carrier packed with lemon rice, potato patties, and mango pickle.',
    familiarPeople: ['Meera', 'Rohan (Age 6)', 'Priya (Age 3)'],
    isMemoryOfTheDay: false,
    createdAt: '2026-08-18T12:00:00Z',
    updatedAt: '2026-09-06T15:00:00Z',
    story: [
      'The spring flowers were in full bloom across the historic lawns. Kamal carried the big wicker basket, while little Rohan was convinced he could catch a peacock feather.',
      'Meera had packed fresh lemon rice and warm puri with sweet mango pickle. Priya sat on your lap feeding breadcrumbs to the sparrows.',
      'We stayed until sunset when the sky turned soft violet, singing nursery rhymes the entire scooter ride home.'
    ],
    familyNotes: [
      {
        id: 'fn-5',
        patientId: 'p-101',
        memoryId: 'family-picnic-lodi',
        authorId: 'cg-02',
        authorName: 'Rohan',
        relation: 'Son',
        text: 'I remember scraping my knee that afternoon, and you put a little cold water and kissed it better. The pain disappeared in a second.',
        date: 'Yesterday',
        avatarInitials: 'R',
        avatarBg: 'bg-orange-500',
        createdAt: '2026-09-08T14:00:00Z',
      },
    ],
    audioNarration: {
      narrator: 'Rohan (Son)',
      relation: 'Memory reading',
      duration: '1:50',
      title: 'Butterflies at Lodi Gardens',
    },
  },
  {
    id: 'shimla-summer',
    patientId: 'p-101',
    title: 'Summer Holiday in Shimla Hills',
    shortDescription: 'The pine-scented mountain air, toy train chugging up the curves, and wooden cottage verandas.',
    dateEra: 'June 1981 • Himachal Pradesh',
    yearApproximate: '1981',
    location: 'The Ridge & Mall Road, Shimla',
    category: 'places',
    emotionalTag: 'Serenity & Wonder',
    emotionalColor: 'bg-purple-100 text-purple-900 border-purple-300',
    companionIntro: 'Breathe in the cool pine breeze of Shimla. What a peaceful mountain journey that was.',
    coverImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
    imageAlt: 'Majestic mountain valley with misty pine forests and morning golden light',
    imageCaption: 'Looking out toward the snow-capped Himalayan peaks with hot cardamom tea.',
    familiarPeople: ['Meera', 'Sister Shanti', 'Brother-in-law Ramesh'],
    isMemoryOfTheDay: false,
    createdAt: '2026-08-19T13:00:00Z',
    updatedAt: '2026-09-05T16:00:00Z',
    story: [
      'Escaping the Delhi heat, the little narrow-gauge Kalka-Shimla train entered the lush hills through tunnel after tunnel.',
      'Every stop smelled of roasting mountain corn and mountain pines. You wore your hand-knitted lavender woolen cardigan.',
      'In the evenings, you walked along Mall Road, stopping at the old bookshop to buy books of Hindi poems and wooden toys for the home.'
    ],
    familyNotes: [
      {
        id: 'fn-6',
        patientId: 'p-101',
        memoryId: 'shimla-summer',
        authorId: 'cg-01',
        authorName: 'Priya',
        relation: 'Daughter',
        text: 'You brought back small pine cones in your luggage and painted them gold for our display shelf. I still keep two in my room.',
        date: '5 days ago',
        avatarInitials: 'P',
        avatarBg: 'bg-emerald-600',
        createdAt: '2026-09-04T10:00:00Z',
      },
    ],
    audioNarration: {
      narrator: 'Priya (Daughter)',
      relation: 'Story note',
      duration: '2:05',
      title: 'The Toy Train to the Clouds',
    },
  },
  {
    id: 'diwali-celebration',
    patientId: 'p-101',
    title: 'Diwali Gathering with the Whole Family',
    shortDescription: 'One hundred terracotta diyas lit along the parapet, homemade kaju katli, and sparklers in the yard.',
    dateEra: 'November 1998 • Jaipur',
    yearApproximate: '1998',
    location: 'Shanti Path, Jaipur',
    category: 'celebrations',
    emotionalTag: 'Light & Warmth',
    emotionalColor: 'bg-amber-100 text-amber-900 border-amber-300',
    companionIntro: 'Happy Diwali! Remember the gentle golden glow of all those diyas you arranged.',
    coverImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&auto=format&fit=crop&q=80',
    imageAlt: 'Terracotta oil lamps glowing brightly with warm festival light',
    imageCaption: 'The rangoli of rice flour and orange marigolds you created at the entrance.',
    familiarPeople: ['Meera', 'Rohan', 'Priya', 'Cousins & Neighbors'],
    isMemoryOfTheDay: false,
    createdAt: '2026-08-20T14:00:00Z',
    updatedAt: '2026-09-04T14:00:00Z',
    story: [
      'From 4 o’clock in the afternoon, the house was filled with the aroma of freshly fried mathris and simmering milk for kheer.',
      'You patiently showed Rohan and Priya how to soak the cotton wicks in mustard oil so the diyas would stay lit all through the auspicious night.',
      'When all the lamps were placed along the terrace, you all stood back together and admired how the whole lane was illuminated in peaceful gold.'
    ],
    familyNotes: [
      {
        id: 'fn-7',
        patientId: 'p-101',
        memoryId: 'diwali-celebration',
        authorId: 'cg-02',
        authorName: 'Rohan',
        relation: 'Son',
        text: 'No Diwali sweets in any sweet shop ever compare to the besan laddoos you made with warm ghee, Papa.',
        date: 'A week ago',
        avatarInitials: 'R',
        avatarBg: 'bg-orange-500',
        createdAt: '2026-09-02T16:00:00Z',
      },
    ],
    audioNarration: {
      narrator: 'Rohan (Son)',
      relation: 'Family note',
      duration: '1:40',
      title: 'A Hundred Golden Lamps',
    },
  },
  {
    id: 'first-car-padmini',
    patientId: 'p-101',
    title: 'Our First Sky-Blue Premier Padmini',
    shortDescription: 'The shiny blue car with chrome bumpers that Kamal parked proudly in front of the house.',
    dateEra: '1983 • New Delhi',
    yearApproximate: '1983',
    location: 'Mayur Vihar, New Delhi',
    category: 'things',
    emotionalTag: 'Milestone Pride',
    emotionalColor: 'bg-cyan-100 text-cyan-900 border-cyan-300',
    companionIntro: 'Do you remember the proud day the blue family car arrived in the driveway?',
    coverImage: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&auto=format&fit=crop&q=80',
    imageAlt: 'Classic vintage automobile on a quiet green suburban street',
    imageCaption: 'Registration number DHC-4128. It took us to Agra, Jaipur, and Haridwar.',
    familiarPeople: ['Meera', 'Neighbor Mr. Verma'],
    isMemoryOfTheDay: false,
    createdAt: '2026-08-21T15:00:00Z',
    updatedAt: '2026-09-03T11:00:00Z',
    story: [
      'You had saved for four years for that car. When you drove it through the colony gates, all the neighborhood children gathered around to see the gleaming blue paint.',
      'Grandmother brought a tray with turmeric, vermillion, and fresh coconut to do the ceremonial puja on the front bumper.',
      'Our very first drive was to India Gate at midnight for ice cream. The windows were rolled down, and the summer night breeze was wonderful.'
    ],
    familyNotes: [
      {
        id: 'fn-8',
        patientId: 'p-101',
        memoryId: 'first-car-padmini',
        authorId: 'cg-01',
        authorName: 'Priya',
        relation: 'Daughter',
        text: 'Papa kept that little magnetic Ganesha statue on the dashboard. I still remember the click sound of the glove compartment!',
        date: '3 days ago',
        avatarInitials: 'P',
        avatarBg: 'bg-emerald-600',
        createdAt: '2026-09-06T13:00:00Z',
      },
    ],
    audioNarration: {
      narrator: 'Priya (Daughter)',
      relation: 'Memory voice',
      duration: '2:15',
      title: 'Midnight Ice Cream in the Blue Car',
    },
  },
  {
    id: 'grandmothers-kitchen',
    patientId: 'p-101',
    title: 'Grandmother’s Sweet Bikaner Kitchen',
    shortDescription: 'Brass handis on slow coal embers, cardamom tea, and crisp flaky puris.',
    dateEra: '1965 • Bikaner, Rajasthan',
    yearApproximate: '1965',
    location: 'Old Walled City, Bikaner',
    category: 'childhood',
    emotionalTag: 'Comfort & Taste',
    emotionalColor: 'bg-orange-100 text-orange-900 border-orange-300',
    companionIntro: 'The warm scent of spices and jaggery in grandmother’s beloved kitchen.',
    coverImage: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=1200&auto=format&fit=crop&q=80',
    imageAlt: 'Traditional warm kitchen shelf with brass vessels and aromatic spices',
    imageCaption: 'Grandmother sat on a low wooden stool, stirring sweet halwa with endless patience.',
    familiarPeople: ['Dadi (Grandmother)', 'Maa', 'Sister Shanti'],
    isMemoryOfTheDay: false,
    createdAt: '2026-08-22T16:00:00Z',
    updatedAt: '2026-09-02T09:00:00Z',
    story: [
      'Grandmother’s kitchen had low lime-plastered walls and shelves lined with polished brass canisters that caught the morning light.',
      'No one could roll a rounder paratha than Dadi. She would hand you a small lump of warm dough so you could practice making tiny rotis of your own.',
      'The best moment was when the fresh ghee arrived from the village dairy. The entire room filled with a rich sweetness that made everyone feel at home.'
    ],
    familyNotes: [
      {
        id: 'fn-9',
        patientId: 'p-101',
        memoryId: 'grandmothers-kitchen',
        authorId: 'cg-02',
        authorName: 'Rohan',
        relation: 'Son',
        text: 'You inherited Grandma’s exact recipe for sooji halwa, Papa. Every time you made it on rain days, it felt magical.',
        date: '6 days ago',
        avatarInitials: 'R',
        avatarBg: 'bg-orange-500',
        createdAt: '2026-09-03T15:00:00Z',
      },
    ],
    audioNarration: {
      narrator: 'Rohan (Son)',
      relation: 'Family story',
      duration: '1:55',
      title: 'The Scent of Cinnamon and Ghee',
    },
  },
  {
    id: 'monsoon-terrace',
    patientId: 'p-101',
    title: 'First Monsoon Rain on the Open Terrace',
    shortDescription: 'The intoxicating fragrance of dry earth meeting first raindrops (Petrichor) and piping hot pakoras.',
    dateEra: 'July 1991 • Jaipur',
    yearApproximate: '1991',
    location: 'Rooftop Terrace, Jaipur',
    category: 'places',
    emotionalTag: 'Refreshing Wonder',
    emotionalColor: 'bg-teal-100 text-teal-900 border-teal-300',
    companionIntro: 'Feel the cool droplets of the July monsoon rain. How refreshing the terrace was.',
    coverImage: 'https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?w=1200&auto=format&fit=crop&q=80',
    imageAlt: 'Raindrops falling peacefully on lush green leaves with misty atmosphere',
    imageCaption: 'Watching peacocks call from neighboring trees as dark monsoon clouds rolled in.',
    familiarPeople: ['Meera', 'Priya', 'Rohan'],
    isMemoryOfTheDay: false,
    createdAt: '2026-08-23T17:00:00Z',
    updatedAt: '2026-09-01T14:00:00Z',
    story: [
      'After weeks of scorching Rajasthan heat, the afternoon sky turned a dramatic slate gray. The sudden gust of wind brought the scent of wet soil.',
      'You ran upstairs to gather the laundry drying on the terrace line, but ended up laughing and holding your hands out to catch the big cool drops.',
      'Meera fried onion pakoras downstairs, and you all sat on the shaded veranda listening to the steady rain drumming on the tin awning.'
    ],
    familyNotes: [
      {
        id: 'fn-10',
        patientId: 'p-101',
        memoryId: 'monsoon-terrace',
        authorId: 'cg-01',
        authorName: 'Priya',
        relation: 'Daughter',
        text: 'I can still hear you laughing as you danced with me in the rain, Papa! You didn’t even care about getting soaked.',
        date: '2 days ago',
        avatarInitials: 'P',
        avatarBg: 'bg-emerald-600',
        createdAt: '2026-09-07T16:00:00Z',
      },
    ],
    audioNarration: {
      narrator: 'Priya (Daughter)',
      relation: 'Voice note',
      duration: '1:35',
      title: 'Dancing in the July Rain',
    },
  },
  {
    id: 'rohans-first-steps',
    patientId: 'p-101',
    title: 'Rohan’s Very First Wobbly Steps',
    shortDescription: 'Letting go of the cane sofa and toddling straight into your open arms with a toothless giggle.',
    dateEra: 'February 1988 • New Delhi',
    yearApproximate: '1988',
    location: 'Living Room, New Delhi',
    category: 'family',
    emotionalTag: 'Pure Wonder',
    emotionalColor: 'bg-yellow-100 text-yellow-900 border-yellow-300',
    companionIntro: 'Here is little Rohan when he first learned to walk. You were so patient and loving.',
    coverImage: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=1200&auto=format&fit=crop&q=80',
    imageAlt: 'Cozy home living room with soft rug and gentle daylight',
    imageCaption: 'Three little steps, a wobble, and a big tumble into your warm embrace.',
    familiarPeople: ['Meera', 'Rohan (11 months old)'],
    isMemoryOfTheDay: false,
    createdAt: '2026-08-24T18:00:00Z',
    updatedAt: '2026-08-31T11:00:00Z',
    story: [
      'It was a calm Sunday afternoon. Rohan was holding on to the edge of the woven cane armchair, eyeing a red plastic ball three feet away.',
      'You knelt on the floral carpet with your arms outstretched, encouraging him with soft words: "Come on beta, come to Papa."',
      'He let go, took one brave step, paused, took two quick wobbles, and collapsed into your arms laughing hysterically. You caught the moment with pure joy.'
    ],
    familyNotes: [
      {
        id: 'fn-11',
        patientId: 'p-101',
        memoryId: 'rohans-first-steps',
        authorId: 'cg-02',
        authorName: 'Rohan',
        relation: 'Son',
        text: 'You have caught me every single time I wobbled throughout my life, Papa. Thank you for always having open arms.',
        date: 'Added today',
        avatarInitials: 'R',
        avatarBg: 'bg-orange-500',
        createdAt: '2026-09-09T07:00:00Z',
      },
    ],
    audioNarration: {
      narrator: 'Rohan (Son)',
      relation: 'Loving note',
      duration: '1:45',
      title: 'Three Little Steps',
    },
  },
  {
    id: 'priyas-dance-recital',
    patientId: 'p-101',
    title: 'Priya’s Arangetram Dance Recital',
    shortDescription: 'The rhythmic chiming of brass ghungroos on the wooden stage and Priya’s radiant smile.',
    dateEra: 'October 1995 • Kamani Auditorium, Delhi',
    yearApproximate: '1995',
    location: 'Kamani Auditorium, New Delhi',
    category: 'celebrations',
    emotionalTag: 'Fatherly Pride',
    emotionalColor: 'bg-indigo-100 text-indigo-900 border-indigo-300',
    companionIntro: 'Priya’s first solo Kathak dance recital. You were so thrilled in the front row.',
    coverImage: 'https://images.unsplash.com/photo-1545231027-637d2f6210f8?w=1200&auto=format&fit=crop&q=80',
    imageAlt: 'Traditional Indian classical dance bells and ornate floral garlands',
    imageCaption: 'Backstage before the curtains parted. You adjusted her fresh jasmine veni.',
    familiarPeople: ['Priya', 'Guru Shrimati Leela', 'Meera'],
    isMemoryOfTheDay: false,
    createdAt: '2026-08-25T19:00:00Z',
    updatedAt: '2026-08-30T10:00:00Z',
    story: [
      'The auditorium was filled with classical music lovers, relatives, and close friends. The smell of fresh white jasmine flowers filled the green room.',
      'You held Priya’s hands before the stage entry and told her: "Dance with your heart, beti. We are already so proud."',
      'When she concluded her final tatkar, the entire hall erupted into a standing ovation. You stood up with tears in your eyes, clapping louder than anyone.'
    ],
    familyNotes: [
      {
        id: 'fn-12',
        patientId: 'p-101',
        memoryId: 'priyas-dance-recital',
        authorId: 'cg-01',
        authorName: 'Priya',
        relation: 'Daughter',
        text: 'I was shaking with nervousness until you held my hand backstage, Papa. That gave me courage for life.',
        date: '4 days ago',
        avatarInitials: 'P',
        avatarBg: 'bg-emerald-600',
        createdAt: '2026-09-05T14:00:00Z',
      },
    ],
    audioNarration: {
      narrator: 'Priya (Daughter)',
      relation: 'Memory reading',
      duration: '2:20',
      title: 'Jasmine Flowers and Dancing Bells',
    },
  },
  {
    id: 'musical-evenings',
    patientId: 'p-101',
    title: 'Sunday Classical Sitar Evenings',
    shortDescription: 'Tuning the rosewood sitar to Raga Yaman while sipping evening cardamom tea as the sun set.',
    dateEra: '1979 • Music Room, Jaipur',
    yearApproximate: '1979',
    location: 'Music Room, Jaipur',
    category: 'things',
    emotionalTag: 'Soulful Melody',
    emotionalColor: 'bg-amber-100 text-amber-900 border-amber-300',
    companionIntro: 'Listen to the gentle vibration of the sitar strings. Music always brought peace to your home.',
    coverImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80',
    imageAlt: 'Acoustic instrument strings and warm vintage songbooks in soft lamplight',
    imageCaption: 'The old rosewood sitar resting against the silk cushion.',
    familiarPeople: ['Meera', 'Ustadji Ali Khan'],
    isMemoryOfTheDay: false,
    createdAt: '2026-08-26T20:00:00Z',
    updatedAt: '2026-08-29T17:00:00Z',
    story: [
      'Every Sunday afternoon without fail, you wiped down your teak sitar with a velvet cloth and tuned the resonant strings to Raga Yaman.',
      'Meera prepared hot cardamom chai and almond biscuits, and sat together near the open window overlooking the quiet garden.',
      'Even when life was busy or challenging, those two hours of quiet melody brought complete stillness and comfort to the house.'
    ],
    familyNotes: [
      {
        id: 'fn-13',
        patientId: 'p-101',
        memoryId: 'musical-evenings',
        authorId: 'cg-02',
        authorName: 'Rohan',
        relation: 'Son',
        text: 'That sitar is still safely placed in the study room, Papa. Whenever we hear Raga Yaman, we hear your peaceful wisdom.',
        date: 'Yesterday',
        avatarInitials: 'R',
        avatarBg: 'bg-orange-500',
        createdAt: '2026-09-08T18:00:00Z',
      },
    ],
    audioNarration: {
      narrator: 'Kamal (Self / Family Note)',
      relation: 'Recorded with Priya',
      duration: '2:40',
      title: 'Raga Yaman in the Evening',
    },
  },
  {
    id: 'mem-13-haridwar',
    patientId: 'p-101',
    title: 'Ganga Aarti at Har Ki Pauri',
    shortDescription: 'Thousands of floating brass lamps on the river Ganga, chanting hymns, and the evening chime of bells.',
    dateEra: 'October 1999 • Haridwar',
    yearApproximate: '1999',
    location: 'Har Ki Pauri, Haridwar',
    category: 'places',
    emotionalTag: 'Deep Peace',
    emotionalColor: 'bg-amber-100 text-amber-900 border-amber-300',
    companionIntro: 'Feel the serenity of the river Ganga at sunset with floating marigolds.',
    coverImage: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=1200&auto=format&fit=crop&q=80',
    imageAlt: 'Golden temple reflections on river water with evening glow',
    imageCaption: 'The sacred steps of Har Ki Pauri with lamps floating downstream.',
    familiarPeople: ['Meera', 'Rohan', 'Priya'],
    isMemoryOfTheDay: false,
    createdAt: '2026-08-27T10:00:00Z',
    updatedAt: '2026-08-28T12:00:00Z',
    story: [
      'The cool autumn breeze swept over the swiftly moving waters of the Ganga. The bells from five different temples began ringing in harmony.',
      'You and Meera bought leaf cups filled with orange marigolds and lit camphor lamps, gently setting them onto the rippling current.',
      'We stood silently for a long time watching the trail of light drift down the river, feeling an overwhelming sense of gratitude and peace.'
    ],
    familyNotes: [
      {
        id: 'fn-14',
        patientId: 'p-101',
        memoryId: 'mem-13-haridwar',
        authorId: 'cg-01',
        authorName: 'Priya',
        relation: 'Daughter',
        text: 'You held my hand so gently that evening so I wouldn’t be frightened by the big crowd. It was one of the calmest moments of my life.',
        date: 'A week ago',
        avatarInitials: 'P',
        avatarBg: 'bg-emerald-600',
        createdAt: '2026-09-02T13:00:00Z',
      },
    ],
    audioNarration: {
      narrator: 'Priya (Daughter)',
      relation: 'Reflective story',
      duration: '2:15',
      title: 'Lamps on the Holy River',
    },
  },
  {
    id: 'mem-14-tulsi',
    patientId: 'p-101',
    title: 'Morning Balcony Tulsi Care & Sparrows',
    shortDescription: 'Watering the fragrant holy basil pot, feeding bajra seeds to sparrows, and welcoming the morning sun.',
    dateEra: 'Daily Tradition • Greater Kailash',
    yearApproximate: '2010 - Present',
    location: 'Veranda Balcony, New Delhi',
    category: 'things',
    emotionalTag: 'Quiet Rhythm',
    emotionalColor: 'bg-emerald-100 text-emerald-900 border-emerald-300',
    companionIntro: 'Your morning balcony routine with the sweet chirping birds and fresh tulsi leaves.',
    coverImage: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1200&auto=format&fit=crop&q=80',
    imageAlt: 'Lush green potted basil plant in warm golden morning sunlight',
    imageCaption: 'The clay pot painted with white chalk designs resting on the balcony ledge.',
    familiarPeople: ['Kamal', 'Neighbor birds'],
    isMemoryOfTheDay: false,
    createdAt: '2026-08-28T07:30:00Z',
    updatedAt: '2026-08-28T07:30:00Z',
    story: [
      'Every morning at 8:30, after drinking a warm glass of water, you step out to the south-facing balcony.',
      'Using the copper pot, you offer gentle water to the roots of the tulsi plant, reciting a quiet blessing for good health.',
      'Within three minutes, four little sparrows perch on the railing waiting for the crushed biscuits and millet seeds you keep in the small wooden bowl.'
    ],
    familyNotes: [
      {
        id: 'fn-15',
        patientId: 'p-101',
        memoryId: 'mem-14-tulsi',
        authorId: 'cg-01',
        authorName: 'Priya',
        relation: 'Daughter',
        text: 'The birds know you by heart, Papa. They chirp happily the second they hear your footsteps on the tiles.',
        date: '2 days ago',
        avatarInitials: 'P',
        avatarBg: 'bg-emerald-600',
        createdAt: '2026-09-07T08:00:00Z',
      },
    ],
    audioNarration: {
      narrator: 'Priya (Daughter)',
      relation: 'Daily blessing',
      duration: '1:30',
      title: 'The Morning Song of the Sparrows',
    },
  },
  {
    id: 'mem-15-kheer',
    patientId: 'p-101',
    title: 'Monsoon Saffron Kheer with Grandchildren',
    shortDescription: 'Slow-simmered basmati rice, crushed green cardamom, and golden slivered almonds made on rainy holidays.',
    dateEra: 'August 2018 • Greater Kailash',
    yearApproximate: '2018',
    location: 'Family Dining Room, New Delhi',
    category: 'family',
    emotionalTag: 'Sweet Togetherness',
    emotionalColor: 'bg-rose-100 text-rose-900 border-rose-300',
    companionIntro: 'The delicious aroma of saffron kheer that brought all the grandchildren to the table.',
    coverImage: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=1200&auto=format&fit=crop&q=80',
    imageAlt: 'Traditional creamy dessert garnished with saffron threads and pistachios in ceramic bowl',
    imageCaption: 'The clay bowls chilled in the refrigerator before the feast began.',
    familiarPeople: ['Priya', 'Rohan', 'Grandchildren Kabir & Ananya'],
    isMemoryOfTheDay: false,
    createdAt: '2026-08-29T15:00:00Z',
    updatedAt: '2026-08-29T15:00:00Z',
    story: [
      'Outside the window, a heavy August downpour was drenching the bougainvillea bushes in pink blossoms.',
      'Inside, the thick milk had been simmering on low flame for two hours, turning an irresistible pale cream color with golden strands of Kashmiri saffron.',
      'Kabir and Ananya kept peeking into the kitchen asking if it was cool enough yet. You gave each of them a spoonful straight from the wooden ladle.'
    ],
    familyNotes: [
      {
        id: 'fn-16',
        patientId: 'p-101',
        memoryId: 'mem-15-kheer',
        authorId: 'cg-02',
        authorName: 'Rohan',
        relation: 'Son',
        text: 'Kabir still asks: "When will Dadu make his special saffron kheer?" You make every holiday unforgettable, Papa.',
        date: 'Yesterday',
        avatarInitials: 'R',
        avatarBg: 'bg-orange-500',
        createdAt: '2026-09-08T19:30:00Z',
      },
    ],
    audioNarration: {
      narrator: 'Rohan (Son)',
      relation: 'Family note',
      duration: '1:50',
      title: 'A Bowl Full of Sweetness',
    },
  },
  {
    id: 'mem-16-mysore-temple',
    patientId: 'p-102',
    title: 'Chamundi Hills Temple Visit at Dawn',
    shortDescription: 'Walking up the stone steps in Mysore, jasmine flowers in hair, and hearing morning temple bells.',
    dateEra: '1975 • Mysore, Karnataka',
    yearApproximate: '1975',
    location: 'Chamundeshwari Temple, Mysore',
    category: 'places',
    emotionalTag: 'Serenity & Faith',
    emotionalColor: 'bg-purple-100 text-purple-900 border-purple-300',
    companionIntro: 'The serene morning ascent to Chamundi Hills surrounded by sandalwood fragrance.',
    coverImage: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200&auto=format&fit=crop&q=80',
    imageAlt: 'South Indian temple gopuram towers against clear morning sky',
    imageCaption: 'The stone Nandi statue resting peacefully halfway up the sacred hill.',
    familiarPeople: ['Meera', 'Rohan (as a toddler)', 'Grandmother Lakshmi'],
    isMemoryOfTheDay: false,
    createdAt: '2026-08-30T06:00:00Z',
    updatedAt: '2026-08-30T06:00:00Z',
    story: [
      'The morning mist hovered over the city of Mysore as the sun rose like a warm red disc.',
      'You climbed the ancient steps with your mother, singing devotional verses from Purandara Dasa.',
      'At the shrine, the priest gave you sweet tulsi water and a garland of fragrant white mogra flowers that kept their scent all through the afternoon.'
    ],
    familyNotes: [
      {
        id: 'fn-17',
        patientId: 'p-102',
        memoryId: 'mem-16-mysore-temple',
        authorId: 'cg-02',
        authorName: 'Rohan',
        relation: 'Son',
        text: 'Amma, your voice singing Purandara Dasa songs in the morning is the most peaceful memory of my childhood.',
        date: '3 days ago',
        avatarInitials: 'R',
        avatarBg: 'bg-emerald-600',
        createdAt: '2026-09-06T10:00:00Z',
      },
    ],
    audioNarration: {
      narrator: 'Rohan (Son)',
      relation: 'Temple story',
      duration: '2:10',
      title: 'Dawn on Chamundi Hill',
    },
  },
];

// ==========================================
// 5. REMINDERS (Minimum 10 - Realistic & Connected)
// ==========================================
export const SEED_REMINDERS: Reminder[] = [
  {
    id: 'rem-1',
    patientId: 'p-101',
    title: 'Donepezil 5mg Tablet',
    category: 'medication',
    period: 'morning',
    timeFormatted: '8:00 AM',
    time24: '08:00',
    instructions: 'Give with breakfast. Helps maintain focus, orientation, and memory clarity.',
    recurrence: 'daily',
    requiresCaregiverValidation: true,
    status: 'pending',
    completedAt: undefined,
    completedBy: undefined,
    medicationDosageNote: '1 tablet with warm milk',
    assignedTo: 'Heena Sharma',
    iconName: 'Pill',
    createdAt: '2026-08-01T07:00:00Z',
    updatedAt: '2026-09-09T08:12:00Z',
  },
  {
    id: 'rem-2',
    patientId: 'p-101',
    title: 'Balcony Sunlight & Tulsi Watering',
    category: 'routine',
    period: 'morning',
    timeFormatted: '8:30 AM',
    time24: '08:30',
    instructions: '15 minutes of gentle morning sun, deep breathing, and watering the tulsi plant.',
    recurrence: 'daily',
    requiresCaregiverValidation: false,
    status: 'completed',
    completedAt: '8:45 AM',
    completedBy: 'Kamal Sharma & Companion',
    assignedTo: 'Kamal & Companion',
    iconName: 'Sun',
    createdAt: '2026-08-01T07:00:00Z',
    updatedAt: '2026-09-09T08:45:00Z',
  },
  {
    id: 'rem-3',
    patientId: 'p-101',
    title: 'Blood Pressure Tablet (Amlodipine 5mg)',
    category: 'medication',
    period: 'morning',
    timeFormatted: '9:00 AM',
    time24: '09:00',
    instructions: 'Take after breakfast with a full glass of lukewarm water.',
    recurrence: 'daily',
    requiresCaregiverValidation: true,
    status: 'completed',
    completedAt: '9:05 AM',
    completedBy: 'Heena Sharma',
    medicationDosageNote: '5mg once daily',
    assignedTo: 'Heena Sharma',
    iconName: 'HeartPulse',
    createdAt: '2026-08-01T07:00:00Z',
    updatedAt: '2026-09-09T09:05:00Z',
  },
  {
    id: 'rem-4',
    patientId: 'p-101',
    title: 'Morning Medication (Care Companion Check-in)',
    category: 'medication',
    period: 'morning',
    timeFormatted: '9:30 AM',
    time24: '09:30',
    instructions: 'Take with a warm glass of water. Daily gentle vitality boost.',
    recurrence: 'daily',
    requiresCaregiverValidation: false,
    status: 'pending',
    completedAt: undefined,
    completedBy: undefined,
    assignedTo: 'Kamal Sharma',
    iconName: 'Pill',
    createdAt: '2026-08-01T07:00:00Z',
    updatedAt: '2026-09-09T09:32:00Z',
  },
  {
    id: 'rem-5',
    patientId: 'p-101',
    title: 'Mid-Morning Hydration & Papaya Break',
    category: 'hydration',
    period: 'morning',
    timeFormatted: '11:00 AM',
    time24: '11:00',
    instructions: 'Drink 250ml tender water and enjoy a bowl of fresh seasonal papaya.',
    recurrence: 'daily',
    requiresCaregiverValidation: false,
    status: 'completed',
    completedAt: '11:10 AM',
    completedBy: 'Kamal & Companion',
    assignedTo: 'Family Aide / Priya',
    iconName: 'GlassWater',
    createdAt: '2026-08-01T07:00:00Z',
    updatedAt: '2026-09-09T11:10:00Z',
  },
  {
    id: 'rem-6',
    patientId: 'p-101',
    title: 'Afternoon Family Scrapbook Story Time',
    category: 'routine',
    period: 'afternoon',
    timeFormatted: '2:30 PM',
    time24: '14:30',
    instructions: 'Revisit 1-2 curated memories together with Priya or listening to the audio narration.',
    recurrence: 'daily',
    requiresCaregiverValidation: false,
    status: 'upcoming',
    assignedTo: 'Kamal & Family',
    iconName: 'BookOpen',
    createdAt: '2026-08-01T07:00:00Z',
    updatedAt: '2026-09-09T07:00:00Z',
  },
  {
    id: 'rem-7',
    patientId: 'p-101',
    title: 'Fresh Coconut Water & Gentle Hydration',
    category: 'custom',
    period: 'afternoon',
    timeFormatted: '4:00 PM',
    time24: '16:00',
    instructions: 'Hydration break with tender coconut water on the veranda overlooking the garden.',
    recurrence: 'daily',
    requiresCaregiverValidation: false,
    status: 'upcoming',
    assignedTo: 'Family Aide / Priya',
    iconName: 'GlassWater',
    createdAt: '2026-08-01T07:00:00Z',
    updatedAt: '2026-09-09T07:00:00Z',
  },
  {
    id: 'rem-8',
    patientId: 'p-101',
    title: 'Evening Classical Ragas & Breathing Walk',
    category: 'routine',
    period: 'evening',
    timeFormatted: '6:00 PM',
    time24: '18:00',
    instructions: 'Soothing instrumental sitar music (Raga Yaman) to ease twilight transition and prevent sundowning.',
    recurrence: 'daily',
    requiresCaregiverValidation: false,
    status: 'upcoming',
    assignedTo: 'Companion & Family',
    iconName: 'Music',
    createdAt: '2026-08-01T07:00:00Z',
    updatedAt: '2026-09-09T07:00:00Z',
  },
  {
    id: 'rem-9',
    patientId: 'p-101',
    title: 'Blood Pressure Log & Gentle Check',
    category: 'routine',
    period: 'evening',
    timeFormatted: '7:30 PM',
    time24: '19:30',
    instructions: 'Digital arm cuff BP recording; normal target around 125/80 mmHg.',
    recurrence: 'daily',
    requiresCaregiverValidation: true,
    status: 'upcoming',
    assignedTo: 'Heena Sharma',
    iconName: 'HeartPulse',
    createdAt: '2026-08-01T07:00:00Z',
    updatedAt: '2026-09-09T07:00:00Z',
  },
  {
    id: 'rem-10',
    patientId: 'p-101',
    title: 'Night Calcium & Warm Turmeric Milk',
    category: 'medication',
    period: 'bedtime',
    timeFormatted: '9:00 PM',
    time24: '21:00',
    instructions: 'Calcium citrate tablet with warm golden milk before sleep.',
    recurrence: 'daily',
    requiresCaregiverValidation: true,
    status: 'upcoming',
    medicationDosageNote: '500mg tablet',
    assignedTo: 'Heena Sharma',
    iconName: 'Moon',
    createdAt: '2026-08-01T07:00:00Z',
    updatedAt: '2026-09-09T07:00:00Z',
  },
  {
    id: 'rem-11',
    patientId: 'p-102',
    title: 'Rivastigmine Transdermal Patch Application',
    category: 'medication',
    period: 'morning',
    timeFormatted: '9:00 AM',
    time24: '09:00',
    instructions: 'Rotate patch site on upper back/chest. Clean and dry skin.',
    recurrence: 'daily',
    requiresCaregiverValidation: true,
    status: 'completed',
    completedAt: '9:15 AM',
    completedBy: 'Rohan Iyer',
    assignedTo: 'Rohan Iyer',
    iconName: 'Pill',
    createdAt: '2026-08-10T08:00:00Z',
    updatedAt: '2026-09-09T09:15:00Z',
  },
  {
    id: 'rem-12',
    patientId: 'p-103',
    title: 'Memantine 10mg Morning Dose',
    category: 'medication',
    period: 'morning',
    timeFormatted: '8:30 AM',
    time24: '08:30',
    instructions: 'Take with warm milk and toast.',
    recurrence: 'daily',
    requiresCaregiverValidation: true,
    status: 'completed',
    completedAt: '8:40 AM',
    completedBy: 'Sunita Verma',
    assignedTo: 'Sunita Verma',
    iconName: 'Pill',
    createdAt: '2026-08-05T08:00:00Z',
    updatedAt: '2026-09-09T08:40:00Z',
  },
];

// ==========================================
// 6. ACTIVITIES (Minimum 10 Records)
// ==========================================
export const SEED_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    patientId: 'p-101',
    type: 'routine',
    title: 'Morning Breakfast & Routine Check-in',
    category: 'Daily Rhythm',
    time: '8:15 AM',
    timestamp: '2026-09-09T08:15:00Z',
    status: 'completed',
    score: 100,
    durationSeconds: 900,
    description: 'Papa enjoyed warm poha and ginger tea. Companion welcomed him with morning orientation greeting.',
    companionFeedback: 'Oriented to Saturday morning immediately upon waking.',
    cognitiveDomain: 'orientation',
    createdAt: '2026-09-09T08:15:00Z',
  },
  {
    id: 'act-2',
    patientId: 'p-101',
    type: 'routine',
    title: 'Morning Balcony Sunlight & Tulsi Watering',
    category: 'Daily Rhythm',
    time: '8:45 AM',
    timestamp: '2026-09-09T08:45:00Z',
    status: 'completed',
    score: 95,
    durationSeconds: 600,
    description: 'Gentle outdoor exposure, water offering, and sparrow watching.',
    companionFeedback: 'Calm mood, smiled at the sparrows, deep breathing completed.',
    cognitiveDomain: 'motor',
    createdAt: '2026-09-09T08:45:00Z',
  },
  {
    id: 'act-3',
    patientId: 'p-101',
    type: 'reminiscence',
    title: "Viewed Memory: Priya's Kathak Dance Recital (1995)",
    category: 'Family Scrapbook',
    time: '9:40 AM',
    timestamp: '2026-09-09T09:40:00Z',
    status: 'completed',
    score: 90,
    durationSeconds: 320,
    description: 'Revisited the photo of Priya in her Kathak bells at Kamani Auditorium.',
    companionFeedback: 'Papa spent 4 minutes looking at the family notes and smiled joyfully.',
    cognitiveDomain: 'memory',
    createdAt: '2026-09-09T09:40:00Z',
  },
  {
    id: 'act-4',
    patientId: 'p-101',
    type: 'game',
    gameType: 'memory-match',
    title: 'Memory Match: Childhood Courtyard Shapes',
    category: 'Cognitive Puzzle',
    time: '10:15 AM',
    timestamp: '2026-09-09T10:15:00Z',
    status: 'completed',
    score: 92,
    stars: 3,
    durationSeconds: 180,
    description: 'Completed 6-card memory match with zero frustration in under 3 minutes.',
    companionFeedback: 'Quick recognition of familiar brass diya and mango tree cards.',
    cognitiveDomain: 'visual-spatial',
    createdAt: '2026-09-09T10:15:00Z',
  },
  {
    id: 'act-5',
    patientId: 'p-101',
    type: 'hydration',
    title: 'Mid-Morning Hydration & Fresh Papaya Slices',
    category: 'Nutrition & Wellness',
    time: '11:00 AM',
    timestamp: '2026-09-09T11:00:00Z',
    status: 'completed',
    score: 100,
    durationSeconds: 300,
    description: 'Drank 250ml water and had fresh papaya slices.',
    companionFeedback: 'Appetite was great and mood cheerful.',
    cognitiveDomain: 'routine',
    createdAt: '2026-09-09T11:00:00Z',
  },
  {
    id: 'act-6',
    patientId: 'p-101',
    type: 'game',
    gameType: 'find-the-object',
    title: 'Find the Object: Old Library Study Desk',
    category: 'Cognitive Puzzle',
    time: '11:30 AM',
    timestamp: '2026-09-09T11:30:00Z',
    status: 'completed',
    score: 88,
    stars: 3,
    durationSeconds: 210,
    description: 'Located brass magnifying glass, fountain pen, and leather book marker.',
    companionFeedback: 'Focused visual attention; reminisced about student days at Delhi University.',
    cognitiveDomain: 'attention',
    createdAt: '2026-09-09T11:30:00Z',
  },
  {
    id: 'act-7',
    patientId: 'p-101',
    type: 'movement',
    title: 'Veranda Flower Observation & Light Stroll',
    category: 'Gentle Mobility',
    time: '12:15 PM',
    timestamp: '2026-09-09T12:15:00Z',
    status: 'completed',
    score: 85,
    durationSeconds: 600,
    description: 'Gentle 10-minute stroll around the veranda observing winter marigolds.',
    companionFeedback: 'Physical balance steady. Papa commented on the yellow petals.',
    cognitiveDomain: 'motor',
    createdAt: '2026-09-09T12:15:00Z',
  },
  {
    id: 'act-8',
    patientId: 'p-101',
    type: 'game',
    gameType: 'what-comes-next',
    title: 'What Comes Next: Daily Tea Sequence',
    category: 'Cognitive Puzzle',
    time: '1:45 PM',
    timestamp: '2026-09-09T13:45:00Z',
    status: 'completed',
    score: 95,
    stars: 3,
    durationSeconds: 150,
    description: 'Identified correct order: boil water, add ginger, strain into clay cup.',
    companionFeedback: 'Excellent sequential recall without assistance.',
    cognitiveDomain: 'executive',
    createdAt: '2026-09-09T13:45:00Z',
  },
  {
    id: 'act-9',
    patientId: 'p-101',
    type: 'reminiscence',
    title: 'Scheduled: Afternoon Reminiscence Scrapbook',
    category: 'Family Scrapbook',
    time: '2:30 PM',
    timestamp: '2026-09-09T14:30:00Z',
    status: 'scheduled',
    description: 'Curated session focusing on favorite university memories in Delhi.',
    cognitiveDomain: 'memory',
    createdAt: '2026-09-09T08:00:00Z',
  },
  {
    id: 'act-10',
    patientId: 'p-102',
    type: 'reminiscence',
    title: 'Carnatic Music Vocal Prompt & Mysore Recollection',
    category: 'Music & Senses',
    time: '10:00 AM',
    timestamp: '2026-09-09T10:00:00Z',
    status: 'completed',
    score: 90,
    durationSeconds: 420,
    description: 'Listened to M.S. Subbulakshmi suprabhatam and shared recollections of Mysore.',
    companionFeedback: 'Hummed along with the melody, highly receptive.',
    cognitiveDomain: 'memory',
    createdAt: '2026-09-09T10:00:00Z',
  },
  {
    id: 'act-11',
    patientId: 'p-103',
    type: 'routine',
    title: 'Awadhi History Radio Listening Session',
    category: 'Auditory Reminiscence',
    time: '11:15 AM',
    timestamp: '2026-09-09T11:15:00Z',
    status: 'completed',
    score: 75,
    durationSeconds: 540,
    description: 'Short audio excerpt of old Lucknow history.',
    companionFeedback: 'Attentive for 7 minutes, then became slightly tired.',
    cognitiveDomain: 'attention',
    createdAt: '2026-09-09T11:15:00Z',
  },
];

// ==========================================
// 7. CLINICAL OBSERVATIONS (Minimum 10)
// ==========================================
export const SEED_OBSERVATIONS: Observation[] = [
  {
    id: 'obs-01',
    patientId: 'p-101',
    practitionerId: 'dr-01',
    practitionerName: 'Dr. Arvind Sen, MD',
    date: '2026-09-08',
    timestamp: '2026-09-08T15:30:00Z',
    domain: 'memory',
    severity: 'positive',
    observationText: 'Remarkable retention during family photo reviews. Patient successfully identified daughter’s 1995 Kathak performance location without prompting.',
    recommendationText: 'Continue daily 15-minute reminiscence sessions. Maintain Raga Yaman audio cues in the late afternoon.',
    metricsSnapshot: {
      engagementScore: 88,
      adherenceRate: 94,
      mocaScoreEstimate: 23,
    },
    isSharedWithCaregiver: true,
    createdAt: '2026-09-08T15:30:00Z',
  },
  {
    id: 'obs-02',
    patientId: 'p-101',
    practitionerId: 'dr-01',
    practitionerName: 'Dr. Arvind Sen, MD',
    date: '2026-09-05',
    timestamp: '2026-09-05T11:00:00Z',
    domain: 'routine',
    severity: 'positive',
    observationText: '100% adherence to Donepezil and BP medication over the past 14 days. Daughter validates prompt intake with morning breakfast.',
    recommendationText: 'Maintain current Donepezil 5mg once daily. Re-evaluate kidney panel in 6 months.',
    metricsSnapshot: {
      engagementScore: 84,
      adherenceRate: 98,
      mocaScoreEstimate: 23,
    },
    isSharedWithCaregiver: true,
    createdAt: '2026-09-05T11:00:00Z',
  },
  {
    id: 'obs-03',
    patientId: 'p-101',
    practitionerId: 'dr-03',
    practitionerName: 'Nalini Raman (OT)',
    date: '2026-09-03',
    timestamp: '2026-09-03T16:15:00Z',
    domain: 'motor',
    severity: 'info',
    observationText: 'Balcony walk gait observed: steady cadence, arm swing bilateral and symmetrical. Plant watering activity provides positive goal-directed motor stimulation.',
    recommendationText: 'Keep walking path clear of loose rugs. Outdoor morning sunlight is assisting circadian entrainment.',
    metricsSnapshot: {
      engagementScore: 86,
      adherenceRate: 90,
    },
    isSharedWithCaregiver: true,
    createdAt: '2026-09-03T16:15:00Z',
  },
  {
    id: 'obs-04',
    patientId: 'p-101',
    practitionerId: 'dr-01',
    practitionerName: 'Dr. Arvind Sen, MD',
    date: '2026-08-28',
    timestamp: '2026-08-28T14:20:00Z',
    domain: 'mood',
    severity: 'positive',
    observationText: 'Affect is consistently cheerful and calm. Zero episodes of agitation or uncharacteristic withdrawal recorded in companion telemetry.',
    recommendationText: 'Reinforce family audio narrations recorded by Priya and Rohan whenever evening fatigue appears.',
    metricsSnapshot: {
      engagementScore: 85,
      adherenceRate: 92,
      mocaScoreEstimate: 23,
    },
    isSharedWithCaregiver: true,
    createdAt: '2026-08-28T14:20:00Z',
  },
  {
    id: 'obs-05',
    patientId: 'p-102',
    practitionerId: 'dr-01',
    practitionerName: 'Dr. Arvind Sen, MD',
    date: '2026-09-07',
    timestamp: '2026-09-07T10:45:00Z',
    domain: 'orientation',
    severity: 'info',
    observationText: 'Meera-ji shows excellent orientation to time of day through the companion interface. Occasional hesitation when asked for exact day of the week.',
    recommendationText: 'Rely on the high-contrast calendar card on home view. Use auditory chime at 9:00 AM.',
    metricsSnapshot: {
      engagementScore: 78,
      adherenceRate: 86,
      mocaScoreEstimate: 20,
    },
    isSharedWithCaregiver: true,
    createdAt: '2026-09-07T10:45:00Z',
  },
  {
    id: 'obs-06',
    patientId: 'p-102',
    practitionerId: 'dr-03',
    practitionerName: 'Nalini Raman (OT)',
    date: '2026-09-01',
    timestamp: '2026-09-01T14:00:00Z',
    domain: 'memory',
    severity: 'positive',
    observationText: 'High responsiveness to tactile memories: silk weaving and temple flower recollections evoke immediate smiling and verbal storytelling.',
    recommendationText: 'Caregiver Rohan encouraged to upload 2-3 more Mysore family photos into the scrapbook.',
    metricsSnapshot: {
      engagementScore: 76,
      adherenceRate: 88,
    },
    isSharedWithCaregiver: true,
    createdAt: '2026-09-01T14:00:00Z',
  },
  {
    id: 'obs-07',
    patientId: 'p-103',
    practitionerId: 'dr-02',
    practitionerName: 'Dr. Sunita Kulkarni, MD',
    date: '2026-09-06',
    timestamp: '2026-09-06T16:00:00Z',
    domain: 'mood',
    severity: 'concern',
    observationText: 'Caregiver reported two episodes of late-afternoon restlessness and pacing near twilight (sundowning). Blood pressure remained elevated (142/88).',
    recommendationText: 'Shift evening walk 30 minutes earlier. Dim harsh white lights and play calming instrumental sarangi by 5:30 PM.',
    metricsSnapshot: {
      engagementScore: 62,
      adherenceRate: 72,
      mocaScoreEstimate: 17,
    },
    isSharedWithCaregiver: true,
    createdAt: '2026-09-06T16:00:00Z',
  },
  {
    id: 'obs-08',
    patientId: 'p-103',
    practitionerId: 'dr-02',
    practitionerName: 'Dr. Sunita Kulkarni, MD',
    date: '2026-08-30',
    timestamp: '2026-08-30T11:30:00Z',
    domain: 'routine',
    severity: 'action_needed',
    observationText: 'Hydration tracking showed suboptimal intake (under 1 liter) on three consecutive days. May exacerbate vascular confusion.',
    recommendationText: 'Caregiver Sunita advised to implement flavored coconut water and lemonade cues after morning meals.',
    metricsSnapshot: {
      engagementScore: 65,
      adherenceRate: 70,
    },
    isSharedWithCaregiver: true,
    createdAt: '2026-08-30T11:30:00Z',
  },
  {
    id: 'obs-09',
    patientId: 'p-104',
    practitionerId: 'dr-01',
    practitionerName: 'Dr. Arvind Sen, MD',
    date: '2026-09-04',
    timestamp: '2026-09-04T12:00:00Z',
    domain: 'attention',
    severity: 'info',
    observationText: 'Completed Find-the-Object puzzle in 3.5 minutes. Visual scanning speed is stable; no signs of visual hallucinations over past 2 weeks.',
    recommendationText: 'Maintain current sensory cognitive games. Avoid rapid flashing animations.',
    metricsSnapshot: {
      engagementScore: 71,
      adherenceRate: 82,
      mocaScoreEstimate: 19,
    },
    isSharedWithCaregiver: true,
    createdAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 'obs-10',
    patientId: 'p-101',
    practitionerId: 'dr-01',
    practitionerName: 'Dr. Arvind Sen, MD',
    date: '2026-08-15',
    timestamp: '2026-08-15T10:00:00Z',
    domain: 'communication',
    severity: 'positive',
    observationText: 'Baseline clinical assessment at 30-day milestone: Speech is articulate and expressive. Word-finding pauses are minimal (approx 2 per conversation).',
    recommendationText: 'Encourage patient to narrate memories directly to the companion voice studio.',
    metricsSnapshot: {
      engagementScore: 82,
      adherenceRate: 90,
      mocaScoreEstimate: 23,
    },
    isSharedWithCaregiver: true,
    createdAt: '2026-08-15T10:00:00Z',
  },
];

// ==========================================
// 8. NARRATIONS (Voice Stories)
// ==========================================
export const SEED_NARRATIONS: Narration[] = [
  {
    id: 'nar-01',
    memoryId: 'childhood-home',
    patientId: 'p-101',
    authorId: 'cg-01',
    authorName: 'Heena Sharma',
    relation: 'Daughter',
    title: 'A Courtyard of Memories',
    durationFormatted: '1:45',
    durationSeconds: 105,
    transcript: 'Papa, do you remember the Jaipur courtyard with the big mango tree? Every morning grandmother sang sweet hymns while the wind chimes danced in the gentle desert breeze.',
    status: 'published',
    createdAt: '2026-08-15T10:00:00Z',
  },
  {
    id: 'nar-02',
    memoryId: 'wedding-day',
    patientId: 'p-101',
    authorId: 'cg-01',
    authorName: 'Heena Sharma',
    relation: 'Daughter',
    title: 'The Song of Two Hearts',
    durationFormatted: '2:30',
    durationSeconds: 150,
    transcript: 'Fifty years ago in Agra, the shehnai played Raga Bilawal as you and Ma tied the holy knot surrounded by red roses and laughing family.',
    status: 'published',
    createdAt: '2026-08-17T12:00:00Z',
  },
  {
    id: 'nar-03',
    memoryId: 'school-graduation',
    patientId: 'p-101',
    authorId: 'cg-02',
    authorName: 'Rohan Iyer / Sharma',
    relation: 'Son',
    title: 'Grandpa’s Proudest Morning',
    durationFormatted: '2:10',
    durationSeconds: 130,
    transcript: 'When they called your name at Delhi University, Grandpa stood up with tears in his eyes. You made our whole family proud.',
    status: 'published',
    createdAt: '2026-08-16T11:00:00Z',
  },
];

// ==========================================
// 9. LOVE NOTES (Heartfelt Messages)
// ==========================================
export const SEED_LOVE_NOTES: LoveNote[] = [
  {
    id: 'ln-01',
    patientId: 'p-101',
    memoryId: 'childhood-home',
    authorId: 'cg-02',
    authorName: 'Rohan',
    relation: 'Son',
    text: 'Papa, whenever you speak about the big courtyard, your eyes sparkle. You taught all of us how to love open skies right there.',
    date: 'Added yesterday',
    avatarInitials: 'R',
    avatarBg: 'bg-orange-500',
    createdAt: '2026-09-08T09:00:00Z',
  },
  {
    id: 'ln-02',
    patientId: 'p-101',
    memoryId: 'childhood-home',
    authorId: 'cg-01',
    authorName: 'Priya',
    relation: 'Daughter',
    text: 'I kept the little brass diya that Grandma gave you from that house on my study desk. It reminds me of your kindness.',
    date: '3 days ago',
    avatarInitials: 'P',
    avatarBg: 'bg-emerald-600',
    createdAt: '2026-09-06T11:00:00Z',
  },
  {
    id: 'ln-03',
    patientId: 'p-101',
    memoryId: 'wedding-day',
    authorId: 'cg-01',
    authorName: 'Priya',
    relation: 'Daughter',
    text: 'The look of tenderness between you and Ma in this wedding album has always been my definition of true companionship.',
    date: '4 days ago',
    avatarInitials: 'P',
    avatarBg: 'bg-emerald-600',
    createdAt: '2026-09-05T12:00:00Z',
  },
  {
    id: 'ln-04',
    patientId: 'p-101',
    authorId: 'cg-01',
    authorName: 'Priya',
    relation: 'Daughter',
    text: 'Good morning Papa! Have a peaceful cup of ginger tea on the veranda. I will see you this afternoon ❤️',
    date: 'Today at 7:30 AM',
    avatarInitials: 'P',
    avatarBg: 'bg-emerald-600',
    createdAt: '2026-09-09T07:30:00Z',
  },
];

// ==========================================
// 10. ALERTS (Caregiver Notifications)
// ==========================================
export const SEED_ALERTS: Alert[] = [
  {
    id: 'alert-1',
    patientId: 'p-101',
    severity: 'info',
    title: 'Morning Routine Successfully Completed',
    description: 'Papa took Donepezil at 8:12 AM and watered the balcony tulsi with high orientation.',
    timeAgo: '1 hr ago',
    timestamp: '2026-09-09T08:45:00Z',
    acknowledged: true,
    actionRecommended: 'No action required; optimal morning rhythm maintained.',
    createdAt: '2026-09-09T08:45:00Z',
  },
  {
    id: 'alert-2',
    patientId: 'p-101',
    severity: 'gentle',
    title: 'Upcoming: Afternoon Hydration & Scrapbook',
    description: 'Scheduled at 2:30 PM. Companion mascot will gently cue the photo album.',
    timeAgo: '30 mins ago',
    timestamp: '2026-09-09T09:15:00Z',
    acknowledged: false,
    actionRecommended: 'Offer fresh coconut water or seasonal fruit alongside.',
    createdAt: '2026-09-09T09:15:00Z',
  },
  {
    id: 'alert-3',
    patientId: 'p-103',
    severity: 'attention',
    title: 'Evening Hydration Target Low',
    description: 'Balram-ji has only logged 600ml fluid intake today. Mild dusk restlessness reported yesterday.',
    timeAgo: '2 hrs ago',
    timestamp: '2026-09-09T07:45:00Z',
    acknowledged: false,
    actionRecommended: 'Prompt caregiver Sunita to offer warm soup or lemonade.',
    createdAt: '2026-09-09T07:45:00Z',
  },
];
